/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package rock_paper_scissors;

import java.awt.Color;
import java.awt.Image;
import java.util.ArrayList;
import java.util.Random;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.border.Border;

/**
 *
 * @author marlon
 */
public class RPS_GUI extends javax.swing.JFrame {
    
    //create borders
    Border gray_border  = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.DARK_GRAY);
    Border orange_border = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.ORANGE);
    
    //image path
    String rock  = "/images/rock.png";
    String paper  = "/images/paper.png";
    String scissors  = "/images/scissor.png";
    
    //create a arraylist
    ArrayList<String> list = new ArrayList<>();
    Random random = new Random();
    int your_wins = 0, computer_wins = 0;
    String random_selection;
   
    /**
     * Creates new form RPS_GUI
     */
    public RPS_GUI() {
        initComponents();
        
        //set borders
        jLabel_You.setBorder(gray_border);
        jLabel_Computer.setBorder(gray_border);
        jLabel_Rock_.setBorder(gray_border);
        jLabel_Paper_.setBorder(gray_border);
        jLabel_Scissors_.setBorder(gray_border);
        
        //display images in jlabels
        displayImage(rock, jLabel_Rock_, 200, 200);
        displayImage(paper, jLabel_Paper_, 200, 200);
        displayImage(scissors, jLabel_Scissors_, 200, 200);
        
        //add items to the list
         list.add(rock);
         list.add(paper);
         list.add(scissors);
         
    }
    
    //create a function to display images in jlabel
    public void displayImage(String imagePath, JLabel label, int width, int height)
    {
        //get the image
        ImageIcon imgIco= new ImageIcon(getClass().getResource(imagePath));
        
        //resize the image
        Image img = imgIco.getImage().getScaledInstance(width, height, Image.SCALE_SMOOTH);
        
        //set image into the jLabel
        label.setIcon(new ImageIcon (img));
        
    }
    
    //create a function to get the winner
   public void getWinner(String you, String computer)
    {
        if(you.equals(computer))
        {
            System.out.println("Draw");
        }
        else if(you.equals(rock))
        {
            if(computer.equals(scissors))
            {
                your_wins++;
                jLabel_YourWins.setText(String.valueOf(your_wins));
            }
            else
            {
                computer_wins++;
                jLabel_ComputerWins.setText(String.valueOf(computer_wins));
            }
        }
        
        else if(you.equals(paper))
        {
            if(computer.equals(rock))
            {
                your_wins++;
                jLabel_YourWins.setText(String.valueOf(your_wins));
            }
            else
            {
                computer_wins++;
                jLabel_ComputerWins.setText(String.valueOf(computer_wins));
            }
        }
        
        else if(you.equals(scissors))
        {
            if(computer.equals(paper))
            {
                your_wins++;
                jLabel_YourWins.setText(String.valueOf(your_wins));
            }
            else
            {
                computer_wins++;
                jLabel_ComputerWins.setText(String.valueOf(computer_wins));
            }
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel_Computer = new javax.swing.JLabel();
        jLabel_Rock_ = new javax.swing.JLabel();
        jLabel_YourWins = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel_ComputerWins = new javax.swing.JLabel();
        jLabel_You = new javax.swing.JLabel();
        jLabel_Scissors_ = new javax.swing.JLabel();
        jLabel_Paper_ = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        exit_Button = new javax.swing.JButton();
        reset_Button = new javax.swing.JButton();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));

        jLabel_Computer.setBackground(new java.awt.Color(204, 255, 204));
        jLabel_Computer.setForeground(new java.awt.Color(0, 0, 0));
        jLabel_Computer.setOpaque(true);

        jLabel_Rock_.setBackground(new java.awt.Color(204, 255, 204));
        jLabel_Rock_.setForeground(new java.awt.Color(0, 0, 0));
        jLabel_Rock_.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_Rock_.setOpaque(true);
        jLabel_Rock_.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_Rock_MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_Rock_MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_Rock_MouseExited(evt);
            }
        });

        jLabel_YourWins.setFont(new java.awt.Font("Helvetica Neue", 0, 36)); // NOI18N
        jLabel_YourWins.setForeground(new java.awt.Color(0, 0, 255));
        jLabel_YourWins.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_YourWins.setText("0");

        jLabel4.setFont(new java.awt.Font("Helvetica Neue", 0, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("-");

        jLabel_ComputerWins.setFont(new java.awt.Font("Helvetica Neue", 0, 36)); // NOI18N
        jLabel_ComputerWins.setForeground(new java.awt.Color(204, 0, 0));
        jLabel_ComputerWins.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_ComputerWins.setText("0");

        jLabel_You.setBackground(new java.awt.Color(204, 255, 204));
        jLabel_You.setForeground(new java.awt.Color(0, 0, 0));
        jLabel_You.setOpaque(true);

        jLabel_Scissors_.setBackground(new java.awt.Color(204, 255, 204));
        jLabel_Scissors_.setForeground(new java.awt.Color(0, 0, 0));
        jLabel_Scissors_.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_Scissors_.setOpaque(true);
        jLabel_Scissors_.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_Scissors_MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_Scissors_MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_Scissors_MouseExited(evt);
            }
        });

        jLabel_Paper_.setBackground(new java.awt.Color(204, 255, 204));
        jLabel_Paper_.setForeground(new java.awt.Color(0, 0, 0));
        jLabel_Paper_.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_Paper_.setOpaque(true);
        jLabel_Paper_.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_Paper_MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_Paper_MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_Paper_MouseExited(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Helvetica Neue", 0, 48)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Computer");

        jLabel10.setFont(new java.awt.Font("Helvetica Neue", 0, 48)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("You");

        exit_Button.setFont(new java.awt.Font("Helvetica Neue", 0, 36)); // NOI18N
        exit_Button.setText("Exit");
        exit_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exit_ButtonActionPerformed(evt);
            }
        });

        reset_Button.setFont(new java.awt.Font("Helvetica Neue", 0, 36)); // NOI18N
        reset_Button.setText("Reset");
        reset_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reset_ButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(107, 107, 107)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel_You, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel_YourWins, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel_ComputerWins, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel_Rock_, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                        .addComponent(jLabel_Paper_, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_Scissors_, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_Computer, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 85, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(reset_Button, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(exit_Button, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(81, 81, 81))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(reset_Button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel_You, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                    .addComponent(jLabel_Computer, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_YourWins, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_ComputerWins, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 109, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel_Rock_, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                        .addComponent(jLabel_Paper_, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                        .addComponent(jLabel_Scissors_, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(exit_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(134, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel_Rock_MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_Rock_MouseClicked
        
        // display rock image
        displayImage(rock, jLabel_You, 200, 200);
        
        // make a random selection
        random_selection = list.get(random.nextInt(list.size()));
        
        // display image 
        displayImage(random_selection, jLabel_Computer, 200, 200);
        getWinner(rock, random_selection);
       
    }//GEN-LAST:event_jLabel_Rock_MouseClicked

    private void jLabel_Rock_MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_Rock_MouseEntered
        // change border
        jLabel_Rock_.setBorder(orange_border);
        
        
    }//GEN-LAST:event_jLabel_Rock_MouseEntered

    private void jLabel_Rock_MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_Rock_MouseExited
        //change border
        jLabel_Rock_.setBorder(gray_border);
    }//GEN-LAST:event_jLabel_Rock_MouseExited

    private void jLabel_Paper_MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_Paper_MouseClicked
       // display paper image
        displayImage(paper, jLabel_You, 200, 200);
        
        // make a random selection
        random_selection = list.get(random.nextInt(list.size()));
        
        // display image 
        displayImage(random_selection, jLabel_Computer, 200, 200);
        getWinner(paper, random_selection);
       
    }//GEN-LAST:event_jLabel_Paper_MouseClicked

    private void jLabel_Paper_MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_Paper_MouseEntered
        // TODO add your handling code here:
        // change border
        jLabel_Paper_.setBorder(orange_border);
    }//GEN-LAST:event_jLabel_Paper_MouseEntered

    private void jLabel_Paper_MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_Paper_MouseExited
        // TODO add your handling code here:
        //change border
        jLabel_Paper_.setBorder(gray_border);
    }//GEN-LAST:event_jLabel_Paper_MouseExited

    private void jLabel_Scissors_MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_Scissors_MouseClicked
        // display paper image
        displayImage(scissors, jLabel_You, 200, 200);
        
        // make a random selection
        random_selection = list.get(random.nextInt(list.size()));
        
        // display image 
        displayImage(random_selection, jLabel_Computer, 200, 200);
        getWinner(scissors, random_selection);
       
    }//GEN-LAST:event_jLabel_Scissors_MouseClicked

    private void jLabel_Scissors_MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_Scissors_MouseEntered
        // TODO add your handling code here:
        // change border
        jLabel_Scissors_.setBorder(orange_border);
    }//GEN-LAST:event_jLabel_Scissors_MouseEntered

    private void jLabel_Scissors_MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_Scissors_MouseExited
        // TODO add your handling code here:
        //change border
        jLabel_Scissors_.setBorder(gray_border);
    }//GEN-LAST:event_jLabel_Scissors_MouseExited

    private void exit_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exit_ButtonActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exit_ButtonActionPerformed

    private void reset_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reset_ButtonActionPerformed
        // TODO add your handling code here:
        computer_wins = 0;
        your_wins = 0;
        jLabel_YourWins.setText("0");
        jLabel_ComputerWins.setText("0");
        
                
        
    }//GEN-LAST:event_reset_ButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RPS_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RPS_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RPS_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RPS_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RPS_GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton exit_Button;
    public javax.swing.JButton jButton1;
    public javax.swing.JLabel jLabel10;
    public javax.swing.JLabel jLabel4;
    public javax.swing.JLabel jLabel9;
    public javax.swing.JLabel jLabel_Computer;
    public javax.swing.JLabel jLabel_ComputerWins;
    public javax.swing.JLabel jLabel_Paper_;
    public javax.swing.JLabel jLabel_Rock_;
    public javax.swing.JLabel jLabel_Scissors_;
    public javax.swing.JLabel jLabel_You;
    public javax.swing.JLabel jLabel_YourWins;
    public javax.swing.JPanel jPanel1;
    public javax.swing.JButton reset_Button;
    // End of variables declaration//GEN-END:variables
}
